# Generated by Django 5.0.3 on 2024-03-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='user',
            table_comment='Таблица пользователей системы',
        ),
    ]
