# Generated by Django 5.0.3 on 2024-03-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='habit',
            table_comment='Таблица привычек пользователей',
        ),
    ]
